version: '3.7'
services:
  match:
    image: "thanakijwanavit/match:latest"
    volumes:
      - q_data:/app/q
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 1
  merger:
    image: "thanakijwanavit/merger:latest"
    volumes:
      - q_data:/app/q
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 1
  monitor:
    image: "thanakijwanavit/monitor:latest"
    volumes:
      - q_data:/app/q
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 1
volumes:
  q_data:
networks:
  overlay:
